version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Astacus789
    ports:
      - "1433:1433"
  blazorapptest2:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BlazorDb;User Id=sa;Password=@Astacus789;TrustServerCertificate=True;
